### ISSUE TITLE
enable darktable or rawtherapee

### ISSUE THREAD

**Issue by marcolam** [IndrekHaav/photoprism-debian#10]
Thank you for your efforts. followed your instrutions I successfully installed photoprism on ubuntu 22.04.
But how can I install darktable or rawtherapee suite to process camera raw file?

**Comment by IndrekHaav** [comment]
As far as I can see, darktable and rawtherapee are in Ubuntu repos, you should be able to simply `apt install` them:

 - https://packages.ubuntu.com/jammy/darktable
 - https://packages.ubuntu.com/jammy/rawtherapee

I don't have any RAW files myself, so I've never needed them.

If this works, let me know and I can add a note about this to the guide.

**Comment by marcolam** [comment]
I installed darktable 4.1.0~git1182.f28dff58-1 according to this: https://docs.photoprism.app/developer-guide/media/raw/
and it works. I have tons of raw files to process,will try a little bit and post some updates.

**Comment by Kh3nsu** [comment]
Hey. I'm using ffmpeg. Is there any benefits of using darktable or rawtherappe?

**Comment by IndrekHaav** [comment]
@Kh3nsu I'm not sure if ffmpeg is suitable for converting RAW files, but if it's working for you (or you don't have RAW files), then there might not be any benefit.

You can always try installing one or the other and testing to see if it makes a difference. If not, uninstall.

**Comment by marcolam** [comment]
I might have to try other solutions because:
1. can't change photo orientation in UI  
2. can't define directory or album cover

orientation auto dectection just won't work on some old photos(over 10 years)

**Comment by IndrekHaav** [comment]
> 1. can't change photo orientation in UI
> 
> 2. can't define directory or album cover

I don't think either of those is even possible with PhotoPrism.
