### ISSUE TITLE
ERRO index: open /opt/photoprism/assets/nasnet/labels.txt: permission denied

### ISSUE THREAD

**Issue by GrumpyMeow** [IndrekHaav/photoprism-debian#14]
I've used the given information to install a Photoprism instance in a Proxmox LXC container.
In the photoprism-log i see the following error: 
```
2023-04-10 12:52:52 ERRO index: open /opt/photoprism/assets/nasnet/labels.txt: permission denied
``` 
This is probably the reason for that i don´t see any categories appear (except "Portrait" and "People"). Although Photoprism is still indexing my photo collection.

If i list the directory, i see that root:root is the owner of these files:
```
root@photoprism-debian:/etc/systemd/system# ls -lai /opt/photoprism/assets/nasnet/          
total 16748
279394 drwxr-xr-x  3 root root     4096 Apr  9 18:42 .
176478 drwxr-xr-x 10 root root     4096 Apr  9 18:42 ..
279395 -rw-r-----  1 root root    11067 Jun  6  2019 labels.txt
279399 -rw-r--r--  1 root root 17118057 Apr 30  2019 saved_model.pb
279396 drwxr-xr-x  2 root root     4096 Apr 30  2019 variables
279400 -rw-r--r--  1 root root       92 Apr  9 18:42 version.txt
```
To resolve this error:
`chown photoprism:photoprism /opt/photoprism/assets/nasnet/*`
And restarted the service: `systemctl restart photoprism`

**Comment by IndrekHaav** [comment]
Thanks for reporting this. I have `sudo chown -R photoprism:photoprism /opt/photoprism` as part of the upgrade procedure, but I'll add it to the install steps as well.
