### ISSUE TITLE
Cannot start service

### ISSUE THREAD

**Issue by tjark-staedtler** [IndrekHaav/photoprism-debian#15]
Hi i cannot start photoprism service because i got this error:

root@kd35-vps001:/var/lib/photoprism# sudo systemctl start photoprism
Job for photoprism.service failed because a fatal signal was delivered to the control process.
See "systemctl status photoprism.service" and "journalctl -xe" for details.

root@kd35-vps001:/var/lib/photoprism# systemctl status photoprism.service 
● photoprism.service - PhotoPrism service
     Loaded: loaded (/etc/systemd/system/photoprism.service; enabled; vendor preset: enabled)
     Active: failed (Result: signal) since Fri 2023-06-09 16:09:48 CEST; 58s ago
    Process: 348637 ExecStart=/opt/photoprism/bin/photoprism up -d (code=killed, signal=ILL)
        CPU: 29ms

**Comment by IndrekHaav** [comment]
Can you post the output of `journalctl -u photoprism.service` ?

**Comment by RahulR100** [comment]
If you have an issue listed in `journalctl` about writing process id to PID file, changing `/etc/systemd/system/photoprism.service` to the following fixed the problem for me:

```
[Unit]
Description=PhotoPrism service
After=network.target

[Service]
Type=simple
WorkingDirectory=/opt/photoprism
EnvironmentFile=/var/lib/photoprism/.env
ExecStart=/opt/photoprism/bin/photoprism up
ExecStop=/opt/photoprism/bin/photoprism down

[Install]
WantedBy=multi-user.target
```

Note the changed start command and the service type = simple. I also removed the user and ran it as root but it should work if you run as photoprism too.

**Comment by IndrekHaav** [comment]
No feedback, so closing.
