### ISSUE TITLE
nodesource deprecated script

### ISSUE THREAD

**Issue by TK-3375** [IndrekHaav/photoprism-debian#18]
When starting the node install script, it prompts you with a warning :

![image](https://github.com/IndrekHaav/photoprism-debian/assets/113793175/e31126c4-4f81-454a-92ba-a0506a552692)

Not sure how bad it is, I guess the guide could use a little update :) Thanks !

**Comment by IndrekHaav** [comment]
Thanks for the heads-up, I'll take a look at rewriting that part. Been meaning to update the guide for Debian 12 anyway.

**Comment by TK-3375** [comment]
Another small mistake (I believe) : at one point you ask to do this : 

`$ sudo chown -R photoprism:photoprism /opt/photoprism
`
But you create that user only a few paragraphs later. Easy to fix even for a complete noob like me, but just to be safe....

**Comment by IndrekHaav** [comment]
Ah, I copied that bit from the upgrade section, but forgot that with a clean install the user isn't created yet. Will fix, thanks!
