### ISSUE TITLE
Unable to start service

### ISSUE THREAD

**Issue by edcactus** [IndrekHaav/photoprism-debian#20]
Thank you for this guide. I have followed all of your steps and am stuck at starting the service. Trying to complete step:

`sudo systemctl enable --now photoprism`

Results in:

`root@stphoto:/# systemctl enable --now photoprism
Job for photoprism.service failed because a fatal signal was delivered to the co                                                                                     ntrol process.
See "systemctl status photoprism.service" and "journalctl -xeu photoprism.servic                                                                                     e" for details.
`

`root@stphoto:/# systemctl status photoprism.service
× photoprism.service - PhotoPrism service
     Loaded: loaded (/etc/systemd/system/photoprism.service; enabled; preset: enabled)
     Active: failed (Result: signal) since Sat 2023-09-30 09:31:25 EDT; 1min 29s ago
    Process: 936 ExecStart=/opt/photoprism/bin/photoprism up -d (code=killed, signal=ILL)
        CPU: 18ms

Sep 30 09:31:25 stphoto systemd[1]: Starting photoprism.service - PhotoPrism service...
Sep 30 09:31:25 stphoto systemd[1]: photoprism.service: Control process exited, code=killed, status=4/ILL
Sep 30 09:31:25 stphoto systemd[1]: photoprism.service: Failed with result 'signal'.
Sep 30 09:31:25 stphoto systemd[1]: Failed to start photoprism.service - PhotoPrism service.
`
`Sep 30 09:28:06 stphoto systemd[1]: Starting photoprism.service - PhotoPrism service...
░░ Subject: A start job for unit photoprism.service has begun execution
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ A start job for unit photoprism.service has begun execution.
░░
░░ The job identifier is 275.
Sep 30 09:28:06 stphoto systemd[1]: photoprism.service: Control process exited, code=killed, status=4/ILL
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ An ExecStart= process belonging to unit photoprism.service has exited.
░░
░░ The process' exit code is 'killed' and its exit status is 4.
Sep 30 09:28:06 stphoto systemd[1]: photoprism.service: Failed with result 'signal'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ The unit photoprism.service has entered the 'failed' state with result 'signal'.
Sep 30 09:28:06 stphoto systemd[1]: Failed to start photoprism.service - PhotoPrism service.
░░ Subject: A start job for unit photoprism.service has failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ A start job for unit photoprism.service has finished with a failure.
░░
░░ The job identifier is 275 and the job result is failed.
`

**Comment by IndrekHaav** [comment]
A few details needed:

 1. OS and version
 2. Were there any errors during the build process?
 3. Did you download the correct version of Tensorflow for your CPU?
 4. Can you run `/opt/photoprism/bin/photoprism -v` and what does it return?

You can also try to start Photoprism directly (not via systemd) with the following command:

```
export $(grep -v ^# /var/lib/photoprism/.env | xargs) && /opt/photoprism/bin/photoprism up
```

If it remains active on your terminal, press `Ctrl+C` to exit. But it should print some more output, maybe something helpful.

**Comment by IndrekHaav** [comment]
No feedback, so closing.
