### ISSUE TITLE
PhotoPrism Installation Packages

### ISSUE THREAD

**Issue by lastzero** [IndrekHaav/photoprism-debian#22]
We now also provide `tar.gz` installation packages with binaries for Linux that you can use as an alternative to Docker (they are  based on the same code and build scripts, just supplied as an archive instead of a Docker image):

- https://dl.photoprism.app/pkg/linux/
- https://dl.photoprism.app/pkg/linux/README.html

If you use these, you should be able to skip all the build steps and just need to make sure that the file/folder permissions are correct and the dependencies (that you want to use) are installed. 

The only requirement should be using a Linux distribution with `glibc >= 2.35`, so for example Ubuntu 22.04 (or later) and Debian Bookworm will work with these binaries, but older Linux distributions may not be compatible.

If you find any other issues, please let us know!

**Comment by IndrekHaav** [comment]
Thanks for the heads-up! That's good news, I'll test it out and update the guide.

I'm assuming the builds include the "regular" (non-AVX) version of Tensorflow?

Do you have plans to publish the builds on Github? That would make linking to the most recent build more convenient.

**Comment by lastzero** [comment]
Oh, that's a great question! Since I've built this on a modern AMD Ryzen CPU, it could be that the AVX2 TensorFlow libraries are bundled. However, the performance difference to the non-AVX version is not big, so we could bundle that instead. Which do you prefer? We will add the packages to the next stable release on GitHub, since we created the current packages after the Docker release (so the build number does not match).

**Comment by lastzero** [comment]
Note that you can also manually replace the TensorFlow libraries in `/opt/photoprism/lib/` with a different version.

**Comment by IndrekHaav** [comment]
> Since I've built this on a modern AMD Ryzen CPU, it could be that the AVX2 TensorFlow libraries are bundled. However, the performance difference to the non-AVX version is not big, so we could bundle that instead. Which do you prefer?

I've seen issues where people are running PhotoPrism on an older CPU that doesn't support AVX2, so probably the non-AVX version would be the safest bet, especially if there's not a lot of difference in terms of performance.

FWIW, if you're planning to use Github Actions for the builds, then currently the non-AVX version should get bundled (though that might change if Github moves their runners to a newer architecture). I know because [I've taken a stab at building PhotoPrism for Linux](https://github.com/IndrekHaav/photoprism-builds/) that way. I'll stop that, of course, now that you're publishing official builds.

**Comment by lastzero** [comment]
> I've seen issues where people are running PhotoPrism on an older CPU that doesn't support AVX2, so probably the non-AVX version would be the safest bet, especially if there's not a lot of difference in terms of performance.

I just checked our build scripts to confirm that the standard TensorFlow libraries (without AVX) are bundled. The `install-tensorflow.sh` script tests CPU support for AVX/AVX2 only if you run it with "auto" as argument, which we do not do in this case.

> FWIW, if you're planning to use Github Actions for the builds, then currently the non-AVX version should get bundled (though that might change if Github moves their runners to a newer architecture).

Due to previous security incidents related to GitHub and running a public CI infrastructure, we currently use a bare-metal server with no direct connection to GitHub to create binaries and run tests (with the exception of the docs repository, which uses GitHub Actions to generate HTML from Markdown). This also allows us to perform manual testing before an official release.

**Comment by IndrekHaav** [comment]
Understood, thanks for the information!

**Comment by lastzero** [comment]
The installation package docs have been added to our public repository, so contributors can send pull requests with improvements:

- https://github.com/photoprism/photoprism/tree/develop/setup/pkg/linux
