### ISSUE TITLE
Hardware Acceleration

### ISSUE THREAD

**Issue by eikaramba** [IndrekHaav/photoprism-debian#25]
Any idea what steps need to be done to support Hardware Acceleration?

I suppose:

1) setting FFmpegEncoder="intel" in the settings, see https://docs.photoprism.app/getting-started/config-files/#file-converters
2) How can i adapt the PHOTOPRISM_INIT variable see https://docs.photoprism.app/getting-started/advanced/transcoding/#intel-quick-sync?

**Comment by IndrekHaav** [comment]
> 2\. How can i adapt the PHOTOPRISM_INIT variable

Add it to the .env file, as described in the guide.
