### ISSUE TITLE
Unable to build the project

### ISSUE THREAD

**Issue by Doraemonsan** [IndrekHaav/photoprism-debian#3]
Hello, everybody I tried to build this project from CentOS Stream8 and Debian11, but I received the same error on both systems, and I couldn't solve it. Can you provide some help?
This is my information：
Virtualized environment ：LXC 4.0.11
System：centos8stream & debian bullseye
Cpu：intel corei5 8500
Memory：4096M
Golang Version：1.17.7
Nodejs Version：centos:16.8.0, debian:16.14.2
TensorFlow Version：libtensorflow-linux-avx2-1.15.2

When I execute make all, I will receive an error prompt after a period of time.
make: *** [Makefile:148：dep-js] error 1

**Comment by IndrekHaav** [comment]
Can you paste here the full output of `sudo make dep-js`?

**Comment by Doraemonsan** [comment]
I got the following：
which: no richgo in (/usr/share/Modules/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/root/bin)
(cd frontend && npm install --silent --legacy-peer-deps)
make: *** [Makefile:148: dep-js] Error 1

**Comment by IndrekHaav** [comment]
Odd, I've not seen that error myself. Just to clarify, is that on CentOS or Debian?

I'm running Photoprism in a Debian 11 LXC container on Proxmox myself, so in principle it should work. Looks like richgo is related to running tests on Golang projects, I don't know why it would even matter when installing NPM dependencies.

What happens if you do `cd frontend && npm install --silent --legacy-peer-deps`? That's basically what `make dep-js` does, except this way you're skipping the Makefile.

**Comment by Doraemonsan** [comment]
I also use Proxmox Debian11 LXC. 
I got this on CentOS：
which: no richgo in (/usr/share/Modules/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/ root/bin)
(cd frontend && npm install --silent --legacy-peer-deps)
make: *** [Makefile:148: dep-js] ERROR 1

I got this on Debian：
(cd frontend && npm install --silent --legacy-peer-deps)
make: *** [Makefile:148：dep-js] ERROR 1

I did not get anything after `cd frontend && npm install --silent --legacy-peer-decall`
![image](https://user-images.githubusercontent.com/21234683/159695038-0820f6ad-a8ae-425d-9e9f-36227d36eb16.png)

**Comment by IndrekHaav** [comment]
Not getting any output after manually running `npm install` is not necessarily a problem, the `--silent` switch is supposed to hide most output except errors.

Still no idea why you're getting the error with `make`, though. I just tried setting up a Debian 11 LXC container from scratch and running through the instructions, and didn't get that error.

Maybe it's not a fatal error, though? You can try running the steps that `make all` executes individually:

```
make dep-tensorflow
make dep-npm
make dep-js
make dep-go
make build-js
```

**Comment by Doraemonsan** [comment]
Executing `make dep-tensorflow` and `make dep-npm`th is very successful, I didn't receive an error, when I executed the `make dep-js`, the same error occurs again.
(cd frontend && npm install --silent --legacy-peer-deps)
make: *** [Makefile:148：dep-js] ERROR 1

**Comment by Doraemonsan** [comment]
If I can't solve this problem, can you provide the LXC template backup package you use?

**Comment by IndrekHaav** [comment]
I'm using the standard Debian 11 LXC template that's available in Proxmox.

What about you, though? That doesn't look like a standard Bash prompt in your screenshots. Is it customised? Or some other shell entirely? Maybe that's causing the error. Can you reproduce the issue on a fresh container with no changes other than what's described in the guide?

**Comment by Doraemonsan** [comment]
I used ZSH as the default shell, I will try to switch the shell to Bash, and build the project again.

**Comment by Doraemonsan** [comment]
Oh well, I tried to rebuild the project with the default LXC template provided by Proxmox, but unfortunately I still received an error in the same place.
![image](https://user-images.githubusercontent.com/21234683/159728979-2ec3f7fa-9f27-42d8-857e-3f4b4699dc47.png)
![image](https://user-images.githubusercontent.com/21234683/159729050-b6723731-da01-4e0c-8782-6d7e8a746c47.png)

This is what I got:
make: *** [Makefile:146: dep-npm] Error 127
![image](https://user-images.githubusercontent.com/21234683/159726769-aacf98d8-0d32-43b2-83e0-c33e77182356.png)

This is my bash history：
```
    1  nano /etc/apt/sources.list
    2  apt update -y && apt upgrade -y
    3  apt install -y net-tools python3-pip unzip unrar tmux lsof  htop git zsh curl
    4  gpg --keyserver https://deb.nodesource.com/gpgkey/nodesource.gpg.key --recv-keys 68576280
    5  gpg --armor --export 68576280 | apt-key add -
    6  nano /etc/apt/sources.list.d/nodesource.list
    7  apt update -y && apt upgrade -y
    8  apt install -y gcc g++  gnupg make autoconf
    9  apt install nodejs -y
   10  npm install -g webpack-cli webpack mini-css-extract-plugin
   11  wget https://golang.org/dl/go1.17.7.linux-amd64.tar.gz
   12  wget wget https://dl.photoprism.org/tensorflow/linux/libtensorflow-linux-avx2-1.15.2.tar.gz
   13  git clone https://github.com/photoprism/photoprism
   14  cd photoprism/
   15  git checkout release
   16  cd ..
   17  tar -C /usr/local -xzf go1.17.7.linux-amd64.tar.gz
   18  ln -s /usr/local/go/bin/go /usr/local/bin/go
   19  tar -C /usr/local -xzf libtensorflow-linux-avx2-1.15.2.tar.gz
   20  ldconfig
   21  cd photoprism/
   22  make all
```

**Comment by IndrekHaav** [comment]
Install `sudo`, I think it's not installed by default in LXC containers (since you're root anyway).

**Comment by Doraemonsan** [comment]
I noticed that I didn't install sudo, I'm trying again.

**Comment by Doraemonsan** [comment]
Thanks, it seems to work correctly.
![image](https://user-images.githubusercontent.com/21234683/159731453-b4a3c7b9-7196-467b-8d7c-5fc394f2d5ee.png)

**Comment by IndrekHaav** [comment]
Cool, thanks for confirming. I'll try and add a note about this to the guide.
