### ISSUE TITLE
Automatic indexing

### ISSUE THREAD

**Issue by kieranc** [IndrekHaav/photoprism-debian#4]
First up, thanks for this guide, it works perfectly. I spent a bit of time trying to figure out how to have my new images indexed automatically since I'm not using webdav, I found a solution so I thought I'd share. Just running photoprism index doesn't work since it's missing the env vars from the .env file, so I made a oneshot systemd service which uses the same format as the existing service, but runs photoprism index using the env vars instead of starting/stopping the service. Maybe this is stupidly obvious, maybe it'll be useful to someone else, I dunno:

```
[Unit]
Description=PhotoPrism index service
After=network.target

[Service]
Type=oneshot
User=photoprism
Group=photoprism
WorkingDirectory=/opt/photoprism
EnvironmentFile=/var/lib/photoprism/.env
ExecStart=/opt/photoprism/bin/photoprism index

[Install]
WantedBy=multi-user.target
```

**Comment by IndrekHaav** [comment]
Hi, thanks for the feedback!

I've never really thought about this aspect, because I've always just triggered indexing manually from the PhotoPrism UI after adding some photos. But if I understand correctly, that service doesn't really accomplish automatic indexing, since a oneshot service should just exit once it's done. Do you trigger it from cron or a systemd timer or something?

**Comment by kieranc** [comment]
Yes I set a systemd timer to run it every 10 minutes, the same could maybe be accomplished as a normal service but its status would appear as failed since it runs, then stops. I think a oneshot service + timer is the appropriate way to run this type of process. I have my originals directory set to my Nextcloud Photos directory where photos are automatically uploaded from my phone, this way they appear in Photoprism shortly after being uploaded with no effort!

**Comment by IndrekHaav** [comment]
Cool! I think this should be possible with a cron job as well, by `source`-ing the .env file before running `photoprism index`. I'll experiment with it a little.

If you want to submit a PR with a quick overview of how you set up the service and timer, though, I'd be happy to add that to the guide as well.

**Comment by IndrekHaav** [comment]
I added a section about running automatic imports using a cron job: https://github.com/IndrekHaav/photoprism-debian/blob/main/README.md#automatic-import

Seems to work on my setup, but I'd appreciate it if you could test it and report if it works for you.

**Comment by kieranc** [comment]
That works, I considered using cron but wasn't sure how to set all the env vars in one as you've done, and having the service, index and timer all using systemd felt cleaner. I'll PR the details of how it's set up

**Comment by IndrekHaav** [comment]
Yeah, that took a bit of fiddling, since `source` doesn't handle comments in the .env file.

I'll review and merge your PR, thanks!
