### ISSUE TITLE
Golang 1.19 is available in backports

### ISSUE THREAD

**Issue by williewillus** [IndrekHaav/photoprism-debian#7]
Photoprism uses Golang 1.19 at the moment, which is now available in bullseye-backports, so installing from google's binaries is no longer necessary.

**Comment by IndrekHaav** [comment]
Thanks, I'll see about mentioning it in the guide. I don't want to replace the existing instructions altogether, though, as I don't know how bullseye-backports will keep up with Golang releases. Plus there's the question of derivative distros like Ubuntu or Raspbian...

**Comment by IndrekHaav** [comment]
Golang is already at 1.19.3, while bullseye-backports has 1.19.1 (not sure about Sid or Ubuntu Kinetic). So I don't think this is a workable solution in the long run, in terms of keeping up with PhotoPrism releases.
